### ISSUE TITLE
This framework doesn't seem to respect my editor settings

### ISSUE THREAD

**Issue by Sambo3975** [lordofduct/spacepuppy-unity-framework-4.0#4]
I have been using [Tri Inspector](https://github.com/codewriter-packages/Tri-Inspector/tree/main) to draw the Inspector and already have several components that depend on it to work properly in the editor. This framework has its own Inspector draw code that seems to be overriding Tri Inspector's code, even though I went into the SP Settings window and disabled SP Inspector.

Is there something I can do to fix this? I have already tried restarting the editor after changing the settings.

**Comment by lordofduct** [comment]
Sure.

This commit that I just did should resolve your issue:
https://github.com/lordofduct/spacepuppy-unity-framework-4.0/commit/0a27cda7cae440f5152a358ec15972a81e86627e

Then you'll just need to add a compiler directive named 'DISABLE_GLOBAL_SPEDITOR' or 'SPEDITOR_IGNORE' in any of the available places. Options are in Player Settings (note this is platform specific so would have to be done for any platforms you edit in), or directly on the assembly definition for com.spacepuppyeditor (search your project for it), directly as a define in the SPEditor.cs file, or any other manner of compiler directive defining you prefer.
